Repository paydaplatformu/payda-support, pull requests merged in 2019-04, with the labels that each got.

#33 Add notes input for donation form
  frontend-payment/src/support-page/form/DonationForm.js
  frontend-payment/src/translations/en.json
  frontend-payment/src/translations/tr.json
Labels: enhancement

#35 Add package price to package selection
  frontend-payment/src/support-page/form/form-components/package/PackageContext.js
  frontend-payment/src/support-page/form/form-components/package/PackageSelect.js
Labels: enhancement

#36 Add default filters for packages
  script-database/.vscode/settings.json
  script-database/src/utils/mongo.ts
  server-payment/README.md
  server-payment/src/container.ts
  server-payment/src/models/Package.ts
  server-payment/src/models/PackageService.ts
  server-payment/src/schema/index.ts
  server-payment/src/services/MockDonationService.ts
  server-payment/src/services/MockPackageService.ts
  server-payment/src/services/MockSubscriptionService.ts
  server-payment/src/services/MockUserService.ts
  server-payment/src/services/MongoPackageService.ts
Labels: bug

#39 Change favicon
  frontend-payment/public/favicon.ico
  frontend-payment/public/favicon.png
  frontend-payment/public/index.html
Labels: enhancement

#40 Fix custom price check
  server-payment/src/models/Errors.ts
  server-payment/src/schema/index.ts
  server-payment/src/services/MongoDonationService.ts
  server-payment/src/services/MongoPackageService.ts
Labels: bug

#41 Update html manifest to show correct information
  frontend-payment/public/index.html
  frontend-payment/public/manifest.json
Labels: autorebase, enhancement

#45 Implement subscription charging logic
  server-payment/src/container.ts
  server-payment/src/models/BaseEntityService.ts
  server-payment/src/models/Package.ts
  server-payment/src/models/PackageService.ts
  server-payment/src/models/RepeatConfig.ts
  server-payment/src/models/Subscription.ts
  server-payment/src/models/SubscriptionManagerService.ts
  server-payment/src/models/SubscriptionService.ts
  server-payment/src/schema/RepeatConfig.ts
  server-payment/src/schema/Subscription.ts
  server-payment/src/schema/context.ts
  server-payment/src/schema/index.ts
  server-payment/src/services/BaseMongoService.ts
  server-payment/src/services/DonationManagerService.ts
  server-payment/src/services/MongoDonationService.ts
  server-payment/src/services/MongoPackageService.ts
  server-payment/src/services/MongoSubscriptionService.ts
  server-payment/src/services/MongoUserService.ts
  server-payment/src/services/PayuService.ts
  server-payment/src/services/SubscriptionManagerService.ts
  server-payment/src/types.ts
Labels: autorebase, enhancement

#47 Update frontend dependencies
  frontend-payment/package.json
  frontend-payment/yarn.lock
Labels: enhancement

#48 Add CORS and improve scope validation
  server-payment/package.json
  server-payment/src/config/index.ts
  server-payment/src/server.ts
  server-payment/src/services/JwtAuthentication.ts
  server-payment/yarn.lock
Labels: autorebase, enhancement

#49 Improve packages list layout
  frontend-payment/.vscode/settings.json
  frontend-payment/src/admin-page/package/PackageCreate.js
  frontend-payment/src/admin-page/package/PackageEdit.js
  frontend-payment/src/admin-page/package/PackageList.js
  frontend-payment/src/constants.js
  frontend-payment/src/utils.js
Labels: autorebase, enhancement

#50 Use predefined apollo errors
  server-payment/src/server.ts
Labels: autorebase, bug

#52 Implement login redirection
  frontend-payment/src/admin-page/AdminPage.js
  frontend-payment/src/admin-page/authProvider.js
  frontend-payment/src/admin-page/i18nProvider.js
  server-payment/src/models/Errors.ts
  server-payment/src/schema/Package.ts
  server-payment/src/schema/index.ts
  server-payment/src/server.ts
Labels: autorebase, enhancement

#53 Complete packages list with filters
  frontend-payment/src/admin-page/package/PackageList.js
  frontend-payment/src/utils.js
  server-payment/src/middleware/errorHandler.ts
  server-payment/src/models/Package.ts
  server-payment/src/schema/Package.ts
  server-payment/src/schema/index.ts
  server-payment/src/server.ts
  server-payment/src/services/BaseMongoService.ts
  server-payment/src/services/MongoPackageService.ts
  server-payment/src/types.ts
Labels: autorebase, enhancement

#58 Make repeat interval customizable
  frontend-payment/src/App.js
  frontend-payment/src/admin-page/package/PackageList.js
  frontend-payment/src/constants.js
  frontend-payment/src/support-page/form/DonationForm.js
  frontend-payment/src/support-page/form/form-components/package/PackageContext.js
  frontend-payment/src/support-page/form/form-components/package/PackageCustomize.js
  frontend-payment/src/support-page/form/form-components/package/PackageSelect.js
  frontend-payment/src/translations/en.json
  frontend-payment/src/translations/tr.json
  script-database/src/utils/migration.ts
  server-payment/src/models/Donation.ts
  server-payment/src/models/Package.ts
  server-payment/src/models/PackageCustomizationConfig.ts
  server-payment/src/models/PackageService.ts
  server-payment/src/schema/Donation.ts
  server-payment/src/schema/Package.ts
  server-payment/src/schema/PackageCustomizationConfig.ts
  server-payment/src/schema/index.ts
  server-payment/src/services/DonationManagerService.ts
  server-payment/src/services/MongoDonationService.ts
  server-payment/src/services/MongoPackageService.ts
Labels: autorebase, enhancement
